### ISSUE TITLE
Join a Twitch chat

### ISSUE THREAD

**Issue by rexim** [tsoding/tsoder#10]
### Pieces

- [x] #12 Add basic Bot FSM that logs messages it receives
- [x] ~~#13 Start tsoder_bot instance on application start~~
- [x] #17 Implement actor that acts as a Twich chat and sends messages to the Bot FSM instance
---

The bot should be able to join a twitch chat and sit there. See https://dev.twitch.tv/docs/v5/guides/irc/

**Comment by rexim** [comment]
Since Twitch uses IRC for their chat functionality we can start with developing a general IRC bot.

**Comment by rexim** [comment]
This might be helpful https://github.com/archaelus/erlirc

**Comment by rexim** [comment]
Keep in mind that erlirc is not available in hex.pm. Install it directly from the git repo
```erlang
{erlirc, {git, "git://github.com/archaelus/erlirc.git"}}
```
